In [1]:
import numpy as np

In [2]:
temperatures = np.array([15.5, 18.2, 22.0, 19.8, 25.1, 14.0, 21.5])

- a) Create a mask to find all temperatures strictly greater than 20.0.
- b) Extract those temperatures into a new array.
- c) Find all temperatures that are greater than 15.0 AND less than 20.0.

In [ ]:
temperatures_greater_than_20 = temperatures > 20.0
temperatures_greater_than_20_array = temperatures[temperatures_greater_than_20]


array([False, False,  True, False,  True, False,  True])

In [8]:
temperatures_with_15_and_20 = temperatures[(temperatures > 15.0) & (temperatures < 20.0)]
temperatures_with_15_and_20

array([15.5, 18.2, 19.8])

In [10]:
primes = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

- a) Use fancy indexing to extract the 2nd, 5th, and 9th prime numbers (remember zero-indexing!).
- b) Reverse the entire array using fancy indexing (Hint: you can use np.arange or standard slicing here, but try using an array of indices).


In [18]:
indices = np.array([1, 4, 8])
primes[indices]

array([ 3, 11, 23])

In [42]:
indices = np.arange(len(primes)-1, -1, -1)

indices

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
primes[indices]

array([29, 23, 19, 17, 13, 11,  7,  5,  3,  2])

## Exercise 3

In [45]:
grid = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

- a) Use boolean indexing to extract all numbers in grid that are divisible by 3. (Hint: use the modulo operator %).
- b) Use fancy indexing to extract the elements at coordinates (0, 3), (1, 1), and (2, 2).

In [46]:
divisible_by_3 = grid % 3 == 0
grid[divisible_by_3]

array([ 3,  6,  9, 12])

In [56]:
grid[[0,1,2], [3,1,2]]  # This will select elements at (0,1), (0,2), and (1,2)

array([ 4,  6, 11])