In [42]:
import numpy as np

In [43]:
np.zeros((3, 4), dtype=str, order='C')

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [44]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.full((2, 3), 0.6)

array([[0.6, 0.6, 0.6],
       [0.6, 0.6, 0.6]])

In [47]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.linspace(5, 100, 5)

array([  5.  ,  28.75,  52.5 ,  76.25, 100.  ])

### Randomly Generate Array

In [49]:
np.random.rand(3, 4)

array([[0.0652865 , 0.42812233, 0.09653092, 0.12715997],
       [0.59674531, 0.226012  , 0.10694568, 0.22030621],
       [0.34982629, 0.46778748, 0.20174323, 0.64040673]])

In [50]:
np.random.seed(2)

100 * np.random.rand(3, 4)

array([[43.59949021,  2.59262318, 54.96624779, 43.53223926],
       [42.03678021, 33.0334821 , 20.4648634 , 61.92709664],
       [29.96546737, 26.68272751, 62.11338328, 52.91420943]])

In [51]:
np.random.randint(0, 100, (3, 4))

array([[67,  4, 42, 51],
       [38, 33, 58, 67],
       [69, 88, 68, 46]], dtype=int32)

### Element-wise operations

In [52]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr += 5
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

In [55]:
print(u, v)

[1 2 3] [4 5 6]


In [56]:
u*v

array([ 4, 10, 18])

In [57]:
def vector_multiply(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result += u[i] * v[i]

    return result

In [58]:
vector_multiply(u, v)

np.float64(32.0)

In [59]:
u.dot(v)

np.int64(32)

In [60]:
v.dot(u)

np.int64(32)

In [61]:
U = np.array([[1, 2, 3], [4, 5, 6]])
U.shape

(2, 3)

In [62]:
def matrix_multiply(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_multiply(U[i], v)

    return result

In [63]:
matrix_multiply(U, v)

array([32., 77.])

In [64]:
U.dot(v)

array([32, 77])

### Matrix-matrix multiplication

In [65]:
V = np.array([[5, 6, 7], [8, 9, 10]])
V.shape

(2, 3)

In [66]:
def matrix_matrix_multiply(U, V):
    assert U.shape[1] == V.shape[1]

    m = U.shape[0]


    result = np.zeros((m, m))
    for i in range(m):
        result[i] = matrix_multiply(V, U[i])

    return result

In [67]:
matrix_matrix_multiply(U, V)

array([[ 38.,  56.],
       [ 92., 137.]])

In [68]:
U.dot(V.T)

array([[ 38,  56],
       [ 92, 137]])

In [80]:
Vs = np.random.randint(0, 5, size=(3, 3))
Vs

array([[3, 1, 2],
       [0, 4, 4],
       [2, 4, 2]], dtype=int32)

In [81]:
Vs_inv = np.linalg.inv(Vs)

Vs_inv

array([[ 0.25  , -0.1875,  0.125 ],
       [-0.25  , -0.0625,  0.375 ],
       [ 0.25  ,  0.3125, -0.375 ]])